# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true

    - name: Build Executables
      run: | 
        #!/usr/bin/env bash
        package_name="shc-exporter"

        platforms=("windows/amd64" "darwin/amd64" "linux/amd64" "darwin/arm64")

        for platform in "${platforms[@]}"
        do
          platform_split=(${platform//\// })
          GOOS=${platform_split[0]}
          GOARCH=${platform_split[1]}
          output_name=$package_name'-'$GOOS'-'$GOARCH
          if [ $GOOS = "windows" ]; then
            output_name+='.exe'
          fi	
          
          env GOOS=$GOOS GOARCH=$GOARCH go build -o bin/$output_name $package
          if [ $? -ne 0 ]; then
              echo 'An error has occurred! Aborting the script execution...'
            exit 1
          fi
        done
        ls -la
    - uses: actions/upload-artifact@v3
      with:
        name: shc-windows
        path: |
          bin/shc-exporter-windows-amd64.exe
        if-no-files-found: warn
    - uses: actions/upload-artifact@v3
      with:
        name: shc-linux
        path: |
          bin/shc-exporter-linux-amd64
        if-no-files-found: warn
    - uses: actions/upload-artifact@v3
      with:
        name: shc-apple-intel
        path: |
          bin/shc-exporter-darwin-amd64
        if-no-files-found: warn
    - uses: actions/upload-artifact@v3
      with:
        name: shc-apple-arm
        path: |
          bin/shc-exporter-darwin-arm64
        if-no-files-found: warn
